set(ARCH armeabi-v7a)
set(HOST arm-linux-androideabi)
set(TOOLCHAIN ${TOOLCHAIN_ROOT}/toolchain-${ARCH})

set(WITH_ARM_THUMB ON)
set(WITH_ARM_NEON ON)

if(WITH_ARM_NEON)
	set(ARM_MFPU "neon")
else()
	set(ARM_MFPU "vfpv3-d16")
endif()

set(NDK_CFLAGS "-fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes")
set(NDK_LDFLAGS "-no-canonical-prefixes")
set(ARCH_CFLAGS "-march=armv7-a -mfloat-abi=softfp -mfpu=${ARM_MFPU}")
set(ARCH_LDFLAGS "-march=armv7-a -Wl,--fix-cortex-a8")

 if(CMAKE_BUILD_TYPE STREQUAL "Release")
	if(WITH_ARM_THUMB)
		set(BUILD_CFLAGS "-mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64")
	else()
		set(BUILD_CFLAGS "-O2 -g -DNDEBUG -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300")
	endif()
elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
	if(WITH_ARM_THUMB)
		set(BUILD_CFLAGS "-O0 -UNDEBUG -marm -fno-omit-frame-pointer")
	else()
		set(BUILD_CFLAGS "-O0 -UNDEBUG -fno-omit-frame-pointer -fno-strict-aliasing")
	endif()
 endif()

set(CROSS_CFLAGS "${NDK_CFLAGS} ${ARCH_CFLAGS} ${BUILD_CFLAGS}")
set(CROSS_LDFLAGS "${NDK_LDFLAGS} ${ARCH_LDFLAGS}")
