set(ARCH armeabi-v7a)
set(HOST arm-linux-androideabi)
set(TARGET armv7a-linux-androideabi${PLATFORM})
set(PROCESSOR arm) # for CMAKE_SYSTEM_PROCESSOR

set(WITH_ARM_THUMB ON)
set(WITH_ARM_NEON ON)

if(WITH_ARM_NEON)
	set(ARM_MFPU "neon")
else()
	set(ARM_MFPU "vfpv3-d16")
endif()

set(NDK_CFLAGS "-DANDROID -fPIC -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -D_FORTIFY_SOURCE=2")
set(NDK_LDFLAGS "-Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--gc-sections -no-canonical-prefixes")
set(ARCH_CFLAGS "-march=armv7-a -mfpu=${ARM_MFPU} -mfloat-abi=softfp")
set(ARCH_LDFLAGS "-march=armv7-a -Wl,--fix-cortex-a8")

set(BUILD_CFLAGS "-g")
 if(CMAKE_BUILD_TYPE STREQUAL "Release")
	if(WITH_ARM_THUMB)
		set(BUILD_CFLAGS "${BUILD_CFLAGS} -mthumb -Os -DNDEBUG")
	else()
		set(BUILD_CFLAGS "${BUILD_CFLAGS} -marm -O2 -DNDEBUG")
	endif()
elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
	if(WITH_ARM_THUMB)
		set(BUILD_CFLAGS "${BUILD_CFLAGS} -mthumb -O0 -UNDEBUG -fno-limit-debug-info")
	else()
		set(BUILD_CFLAGS "${BUILD_CFLAGS} -marm -O0 -UNDEBUG -fno-limit-debug-info")
	endif()
 endif()

set(CROSS_CFLAGS "${NDK_CFLAGS} ${ARCH_CFLAGS} ${BUILD_CFLAGS}")
set(CROSS_LDFLAGS "${NDK_LDFLAGS} ${ARCH_LDFLAGS}")
