set(CMAKE_TOOLCHAIN_ARGS
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_SYSTEM_NAME=Linux
	-DCMAKE_SYSTEM_PROCESSOR=${PROCESSOR}
	-DCMAKE_C_COMPILER=${TOOLCHAIN}/bin/clang
	-DCMAKE_CXX_COMPILER=${TOOLCHAIN}/bin/clang++
	-DCMAKE_C_FLAGS=${CROSS_CFLAGS}
	-DCMAKE_CXX_FLAGS=${CROSS_CFLAGS}
	-DCMAKE_EXE_LINKER_FLAGS=${CROSS_LDFLAGS}
	-DCMAKE_SYSROOT=${TOOLCHAIN}/sysroot
	-DCMAKE_FIND_ROOT_PATH=${TOOLCHAIN}
	-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
	-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
	-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
	-DCMAKE_CROSSCOMPILING=ON
)

set(CONFIGURE_TOOLCHAIN_ARGS_NOFLAGS --host=${HOST} --with-sysroot=${TOOLCHAIN}/sysroot CC=${TOOLCHAIN}/bin/clang CXX=${TOOLCHAIN}/bin/clang++)
set(CONFIGURE_TOOLCHAIN_ARGS ${CONFIGURE_TOOLCHAIN_ARGS_NOFLAGS} CFLAGS=${CROSS_CFLAGS} LDFLAGS=${CROSS_LDFLAGS})
